import { Button, VerticalBox, HorizontalBox, Slider, CheckBox} from "std-widgets.slint";

export component AppWindow inherits Window {
    background: @linear-gradient(90deg, #3c3d3d 0%, #28344d 50%, #0860b3 100%);
    in-out property<string> password: "Password";
    in-out property<int> words_num: 3;
    callback request-generate-password();
    callback request-change-words_num();


    GridLayout {
        spacing: 5px;
        padding: 25px;
        Row {
            HorizontalLayout {
                Text {
                    overflow: TextOverflow.clip;
                    text: "Generated Password";
                    // wrap: TextWrap.word-wrap;
                    color: #ffffffcc;
                    font-italic: false;
                    font-size: 20px;
                    horizontal-alignment: TextHorizontalAlignment.left;
                    vertical-alignment: TextVerticalAlignment.center;
                    
                }       
                // background: red; 
            }
                
        }
        Row {
            Rectangle {
                Text {
                    overflow: TextOverflow.clip;
                    text: "\{root.password}";
                    wrap: TextWrap.char-wrap;
                    color: #ffffffcc;
                    font-italic: false;
                    font-size: 30px;
                    horizontal-alignment: TextHorizontalAlignment.center;
                    vertical-alignment: TextVerticalAlignment.center;
                }
                background: #8a81814c; 
            }
        }
        Row {
                Button {
                    text: "Generate new";
                    clicked => {
                        root.request-generate-password();
                    }
                    preferred-width: 10px;

                }

            }

        Row {
            HorizontalBox {
                Slider {
                    value: root.words_num;
                    minimum: 1;
                    maximum: 5;
                    changed => {
                        root.words_num = self.value;
                        root.request-change-words_num();
                    }
                }
                Text {
                    text: "Number of words: \{root.words_num}";
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    font-size: 20px;
                }
            }
        }
    }

}